---
version: '3.8'
services:
#
# >>> cdcservice
# https://eventuate.io/docs/manual/eventuate-tram/latest/cdc-configuration.html
#
  cdcservice:
    image: eventuateio/eventuate-cdc-service:0.9.0.RELEASE
    ports:
      - 8099:8080
    depends_on:
      - mysql
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
      EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
      EVENTUATELOCAL_CDC_DB_USER_NAME: root
      EVENTUATELOCAL_CDC_DB_PASSWORD: root
      EVENTUATELOCAL_CDC_READER_NAME: ClientEventuateTram
      EVENTUATELOCAL_CDC_MYSQL_BINLOG_CLIENT_UNIQUE_ID: 2
      EVENTUATELOCAL_CDC_BINLOG_CLIENT_ID: 1234567890
      EVENTUATELOCAL_CDC_SOURCE_TABLE_NAME: message
      SPRING_PROFILES_ACTIVE: EventuatePolling
# <<< cdcservice

#
# >>> kafka
#
  zookeeper:
    image: confluentinc/cp-zookeeper:5.2.4
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:5.2.4
    hostname: kafka
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    environment:
      KAFKA_LISTENERS: LC://kafka:29092,LX://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: LC://kafka:29092,LX://${DOCKER_HOST_IP:-localhost}:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LC:PLAINTEXT,LX:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LC
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 60000
# <<< kafka

#
# >>> mysql
#
  mysql:
    image: mysql:5.6
    hostname: mysql
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - "./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
# <<< mysql